/** Diccionarios del chrome del portal: navegación, acceso, cursos y perfil. */

export const SHELL = {
  es: {
    brandAria: 'Aurum Academy — Inicio',
    home: 'Inicio',
    courses: 'Cursos',
    workflows: 'Workflows',
    codex: 'Codex',
    profile: 'Perfil',
    admin: 'Gestión',
    adminRole: 'Gestión',
    myProfile: 'Mi perfil',
    logout: 'Cerrar sesión',
    saving: 'Guardando cambios',
    saved: 'Datos locales guardados',
    openMenu: 'Abrir menú',
    closeMenu: 'Cerrar menú',
  },
  en: {
    brandAria: 'Aurum Academy — Home',
    home: 'Home',
    courses: 'Courses',
    workflows: 'Workflows',
    codex: 'Codex',
    profile: 'Profile',
    admin: 'Admin',
    adminRole: 'Admin',
    myProfile: 'My profile',
    logout: 'Sign out',
    saving: 'Saving changes',
    saved: 'Local data saved',
    openMenu: 'Open menu',
    closeMenu: 'Close menu',
  },
}

export const LOGIN = {
  es: {
    eyebrow: 'EL AULA · ACCESO PRIVADO',
    titleLead: 'Entrá a la ',
    titleAccent: 'sala',
    user: 'Usuario',
    password: 'Contraseña',
    submit: 'Entrar',
    demoLabel: 'Acceso de prueba',
    demoAdmin: 'Gestión',
    demoStudent: 'Alumno',
    back: '← Volver a Aurum Academy',
  },
  en: {
    eyebrow: 'THE ROOM · PRIVATE ACCESS',
    titleLead: 'Step into the ',
    titleAccent: 'room',
    user: 'Username',
    password: 'Password',
    submit: 'Sign in',
    demoLabel: 'Demo access',
    demoAdmin: 'Admin',
    demoStudent: 'Student',
    back: '← Back to Aurum Academy',
  },
}

/** Errores de login — `auth.js` devuelve códigos, acá se traducen. */
export const AUTH_ERRORS = {
  es: {
    invalid_credentials: 'Usuario o contraseña incorrectos.',
    missing_fields: 'Completá usuario y contraseña.',
  },
  en: {
    invalid_credentials: 'Wrong username or password.',
    missing_fields: 'Enter your username and password.',
  },
}

export const HOME = {
  es: {
    eyebrow: 'El aula · sesión abierta',
    greeting: 'Buenas',
    ledeAdmin: 'Panel del equipo. Gestioná alumnos, asigná cursos y seguí el avance de la sala.',
    ledeStudent: 'Tu sala de proyección privada. Retomá donde dejaste y seguí sumando criterio.',
    statCatalog: 'Cursos en catálogo',
    statAssigned: 'Cursos asignados',
    statCompleted: 'Completados',
    statAverage: 'Progreso promedio',
    resumeStarted: 'Continuá donde ibas',
    resumeNew: 'Empezá tu recorrido',
    modules: 'módulos',
    continue: 'Continuar',
    start: 'Empezar',
    opsEyebrow: 'Academy operations',
    deskEyebrow: 'Mesa de evaluación',
    activeTasks: 'tareas activas',
    pendingWorkflows: 'workflows pendientes',
    opsLede: 'Configurá asignaciones, media, Codex y resultados.',
    deskLede: 'Inspeccioná video frame a frame con el Codex siempre a mano.',
    manageTasks: 'Gestionar tareas',
    openWorkflows: 'Abrir workflows',
    catalog: 'Catálogo',
    myCourses: 'Mis cursos',
    seeAll: 'Ver todos',
    emptyCourses: 'Todavía no tenés cursos asignados. El equipo de Aurum te va a asignar el primero muy pronto.',
    adminCta: 'Ir a Gestión — asignar cursos y ver alumnos',
  },
  en: {
    eyebrow: 'The room · session open',
    greeting: 'Hello',
    ledeAdmin: 'Team panel. Manage students, assign courses and track the room.',
    ledeStudent: 'Your private screening room. Pick up where you left off and keep sharpening your eye.',
    statCatalog: 'Courses in catalog',
    statAssigned: 'Assigned courses',
    statCompleted: 'Completed',
    statAverage: 'Average progress',
    resumeStarted: 'Pick up where you were',
    resumeNew: 'Start your path',
    modules: 'modules',
    continue: 'Continue',
    start: 'Start',
    opsEyebrow: 'Academy operations',
    deskEyebrow: 'Evaluation desk',
    activeTasks: 'active tasks',
    pendingWorkflows: 'pending workflows',
    opsLede: 'Configure assignments, media, Codex and results.',
    deskLede: 'Inspect video frame by frame with the Codex always at hand.',
    manageTasks: 'Manage tasks',
    openWorkflows: 'Open workflows',
    catalog: 'Catalog',
    myCourses: 'My courses',
    seeAll: 'See all',
    emptyCourses: 'No courses assigned yet. The Aurum team will assign your first one soon.',
    adminCta: 'Go to Admin — assign courses and view students',
  },
}

export const COURSES_VIEW = {
  es: {
    eyebrowAdmin: 'Catálogo completo',
    eyebrowStudent: 'Tu programa',
    title: 'Cursos',
    ledeAdmin: 'Todos los cursos disponibles en Aurum Academy.',
    ledeStudent: 'Los cursos que el equipo te asignó. Cada uno te acerca a la certificación y a la red de evaluadores.',
    availableOne: 'curso disponible',
    availableMany: 'cursos disponibles',
    summaryAria: 'cursos disponibles',
    empty: 'Todavía no tenés cursos asignados. Escribinos si creés que debería haber alguno acá.',
  },
  en: {
    eyebrowAdmin: 'Full catalog',
    eyebrowStudent: 'Your program',
    title: 'Courses',
    ledeAdmin: 'Every course available in Aurum Academy.',
    ledeStudent: 'The courses the team assigned you. Each one brings you closer to certification and the evaluator network.',
    availableOne: 'course available',
    availableMany: 'courses available',
    summaryAria: 'courses available',
    empty: 'No courses assigned yet. Write to us if you think one should be here.',
  },
}

export const COURSE_CARD = {
  es: {
    edition: 'Aurum Academy · Programa',
    certified: 'Certificado',
    modules: 'módulos',
    review: 'Repasar',
    continue: 'Continuar',
    start: 'Empezar',
  },
  en: {
    edition: 'Aurum Academy · Program',
    certified: 'Certified',
    modules: 'modules',
    review: 'Review',
    continue: 'Continue',
    start: 'Start',
  },
}

export const PROFILE = {
  es: {
    eyebrow: 'Tu ficha de sala',
    title: 'Perfil',
    lede: 'Tu identidad profesional, tu recorrido y las credenciales que ya firmaste.',
    statsAria: 'Resumen del perfil',
    courses: 'cursos',
    certificates: 'certificados',
    noName: 'Sin nombre',
    adminRole: 'Equipo · Gestión',
    noCraft: 'Oficio sin definir',
    fieldName: 'Nombre',
    fieldCraft: 'Oficio',
    fieldEmail: 'Email',
    fieldBio: 'Bio',
    bioHint: 'Una línea sobre tu mirada.',
    craftPlaceholder: 'Fotografía, montaje, color…',
    bioPlaceholder: 'Contá quién sos como cineasta.',
    save: 'Guardar cambios',
    saved: 'Guardado',
    certificatesTitle: 'Certificados',
    adminNoCourses: 'La gestión no cursa: administrás la sala.',
    noCertificates: 'Todavía no tenés certificados. Completá un curso para firmar el primero.',
    certifiedEvaluator: 'Evaluador certificado',
    view: 'Ver',
    progressTitle: 'Avance',
    noAssigned: 'Sin cursos asignados aún.',
  },
  en: {
    eyebrow: 'Your room record',
    title: 'Profile',
    lede: 'Your professional identity, your path and the credentials you already signed.',
    statsAria: 'Profile summary',
    courses: 'courses',
    certificates: 'certificates',
    noName: 'No name',
    adminRole: 'Team · Admin',
    noCraft: 'Craft not set',
    fieldName: 'Name',
    fieldCraft: 'Craft',
    fieldEmail: 'Email',
    fieldBio: 'Bio',
    bioHint: 'One line about how you see.',
    craftPlaceholder: 'Cinematography, editing, color…',
    bioPlaceholder: 'Tell us who you are as a filmmaker.',
    save: 'Save changes',
    saved: 'Saved',
    certificatesTitle: 'Certificates',
    adminNoCourses: 'Admins do not take courses: you run the room.',
    noCertificates: 'No certificates yet. Complete a course to sign your first one.',
    certifiedEvaluator: 'Certified evaluator',
    view: 'View',
    progressTitle: 'Progress',
    noAssigned: 'No courses assigned yet.',
  },
}

export const CERTIFICATE = {
  es: {
    aria: 'Certificado de finalización',
    edition: 'EDICIÓN CERTIFICADA',
    kicker: 'CERTIFICADO DE FINALIZACIÓN',
    rationale: 'Por demostrar mirada, criterio y consistencia en la evaluación de imagen generativa bajo estándares cinematográficos.',
    discipline: 'EVALUACIÓN AUDIOVISUAL IA',
    standard: 'ESTÁNDAR',
    validation: 'VALIDACIÓN INSTITUCIONAL',
    issuer: 'Dirección académica · Emisor',
  },
  en: {
    aria: 'Certificate of completion',
    edition: 'CERTIFIED EDITION',
    kicker: 'CERTIFICATE OF COMPLETION',
    rationale: 'For demonstrating eye, judgement and consistency in evaluating generative imagery against cinematic standards.',
    discipline: 'AI AUDIOVISUAL EVALUATION',
    standard: 'STANDARD',
    validation: 'INSTITUTIONAL VALIDATION',
    issuer: 'Academic direction · Issuer',
  },
}

export const PLAYER = {
  es: {
    quizEyebrow: 'Comprobación',
    wrong: 'Esa no es. Volvé a mirar y probá de nuevo.',
    notInProgram: 'Este curso no está en tu programa',
    moduleOf: 'Módulo {n} de {total}',
    module: 'Módulo',
    progressSaved: 'Progreso guardado',
    answerToContinue: 'Respondé la comprobación para seguir',
    confirm: 'Confirmar',
    previous: 'Anterior',
    next: 'Siguiente',
    finish: 'Finalizar',
    askAssign: 'Pedile al equipo de Aurum que te lo asigne.',
    backToCourses: 'Volver a cursos',
    certificate: 'Certificado',
    courseDone: 'Terminaste el curso.',
    signedLead: 'Firmaste',
    signedTail: 'Sumaste criterio a tu ojo y un paso más hacia la red de evaluadores de Aurum.',
  },
  en: {
    quizEyebrow: 'Checkpoint',
    wrong: 'Not quite. Look again and try once more.',
    notInProgram: 'This course is not in your program',
    moduleOf: 'Module {n} of {total}',
    module: 'Module',
    progressSaved: 'Progress saved',
    answerToContinue: 'Answer the checkpoint to continue',
    confirm: 'Confirm',
    previous: 'Previous',
    next: 'Next',
    finish: 'Finish',
    askAssign: 'Ask the Aurum team to assign it to you.',
    backToCourses: 'Back to courses',
    certificate: 'Certificate',
    courseDone: 'You finished the course.',
    signedLead: 'You signed',
    signedTail: 'You sharpened your eye and moved one step closer to the Aurum evaluator network.',
  },
}

export const ADMIN_VIEW = {
  es: {
    eyebrow: 'Panel del equipo',
    title: 'Gestión',
    lede: 'Asigná cursos y seguí el avance de cada alumno. Los cambios se guardan al instante.',
    overviewAria: 'Resumen de gestión',
    activeStudents: 'Alumnos activos',
    assignments: 'Asignaciones',
    certifications: 'Certificaciones',
    assigned: 'asignados',
    certified: 'Certificado',
    notAssigned: 'No asignado',
    assignedLabel: 'Asignado',
    assign: 'Asignar',
  },
  en: {
    eyebrow: 'Team panel',
    title: 'Admin',
    lede: 'Assign courses and track each student. Changes are saved instantly.',
    overviewAria: 'Admin summary',
    activeStudents: 'Active students',
    assignments: 'Assignments',
    certifications: 'Certifications',
    assigned: 'assigned',
    certified: 'Certified',
    notAssigned: 'Not assigned',
    assignedLabel: 'Assigned',
    assign: 'Assign',
  },
}

export const ADMIN_HUB = {
  es: {
    eyebrow: 'Academy operations',
    title: 'Gestión',
    lede: 'Configuración, asignaciones y revisión desde una única mesa.',
    evaluators: 'evaluadores',
    tasks: 'tareas',
    submissions: 'submissions',
    tabPeople: 'Personas',
    tabWorkflows: 'Workflows',
    tabTasks: 'Tareas',
    tabCodex: 'Codex',
    tabResults: 'Resultados',
    sent: 'enviadas',
    roleStudent: 'Alumno',
    roleExpert: 'Experto',
    enabledWorkflows: 'Workflows habilitados',
    courses: 'Cursos',
    people: 'personas',
    paused: 'Pausado',
    active: 'Activo',
    edit: 'Editar',
    workflowNotFound: 'Workflow no encontrado.',
    workflowEnabled: 'Workflow habilitado',
    rubricDimensions: 'Dimensiones de rúbrica · una por línea',
    primaryReasons: 'Razones principales · una por línea',
    codexCategories: 'Categorías Codex visibles · vacío muestra todas',
    saveConfig: 'Guardar configuración',
    tasksLede: 'Creá la consigna, cargá outputs y asigná evaluadores.',
    newTask: 'Nueva tarea',
    outputs: 'outputs',
    assignedCount: 'asignados',
    taskNotFound: 'Tarea no encontrada.',
    taskEditor: 'Editor de tarea',
    workflow: 'Workflow',
    status: 'Estado',
    mode: 'Modo',
    taskTitle: 'Título',
    prompt: 'Prompt',
    objective: 'Objetivo',
    priority: 'Prioridad',
    outputsHead: 'Outputs',
    output: 'Output',
    label: 'Label',
    sourceUrl: 'URL o ruta pública',
    fps: 'FPS',
    width: 'Ancho',
    height: 'Alto',
    assignEvaluators: 'Asignar evaluadores',
    saveTask: 'Guardar tarea',
    codexLede: 'tags disponibles para evidencia.',
    newTag: 'Nuevo tag',
    category: 'Categoría',
    definition: 'Definición',
    useWhen: 'Usar cuando',
    doNotUseWhen: 'No usar cuando',
    defaultSeverity: 'Severidad default',
    save: 'Guardar',
    remove: 'Eliminar',
    pickTag: 'Seleccioná un tag para editarlo.',
    issues: 'issues',
    pendingReview: 'pendiente de revisión',
    approve: 'Aprobar',
    requestChanges: 'Pedir cambios',
    changesNote: 'Revisá la evidencia y volvé a enviar.',
    noResults: 'Todavía no hay evaluaciones enviadas.',
  },
  en: {
    eyebrow: 'Academy operations',
    title: 'Admin',
    lede: 'Configuration, assignments and review from a single desk.',
    evaluators: 'evaluators',
    tasks: 'tasks',
    submissions: 'submissions',
    tabPeople: 'People',
    tabWorkflows: 'Workflows',
    tabTasks: 'Tasks',
    tabCodex: 'Codex',
    tabResults: 'Results',
    sent: 'submitted',
    roleStudent: 'Student',
    roleExpert: 'Expert',
    enabledWorkflows: 'Enabled workflows',
    courses: 'Courses',
    people: 'people',
    paused: 'Paused',
    active: 'Active',
    edit: 'Edit',
    workflowNotFound: 'Workflow not found.',
    workflowEnabled: 'Workflow enabled',
    rubricDimensions: 'Rubric dimensions · one per line',
    primaryReasons: 'Primary reasons · one per line',
    codexCategories: 'Visible Codex categories · empty shows all',
    saveConfig: 'Save configuration',
    tasksLede: 'Write the brief, load outputs and assign evaluators.',
    newTask: 'New task',
    outputs: 'outputs',
    assignedCount: 'assigned',
    taskNotFound: 'Task not found.',
    taskEditor: 'Task editor',
    workflow: 'Workflow',
    status: 'Status',
    mode: 'Mode',
    taskTitle: 'Title',
    prompt: 'Prompt',
    objective: 'Objective',
    priority: 'Priority',
    outputsHead: 'Outputs',
    output: 'Output',
    label: 'Label',
    sourceUrl: 'Public URL or path',
    fps: 'FPS',
    width: 'Width',
    height: 'Height',
    assignEvaluators: 'Assign evaluators',
    saveTask: 'Save task',
    codexLede: 'tags available for evidence.',
    newTag: 'New tag',
    category: 'Category',
    definition: 'Definition',
    useWhen: 'Use when',
    doNotUseWhen: 'Do not use when',
    defaultSeverity: 'Default severity',
    save: 'Save',
    remove: 'Remove',
    pickTag: 'Pick a tag to edit it.',
    issues: 'issues',
    pendingReview: 'pending review',
    approve: 'Approve',
    requestChanges: 'Request changes',
    changesNote: 'Review the evidence and submit again.',
    noResults: 'No submitted evaluations yet.',
  },
}
