/** Diccionarios de la mesa de evaluación: workflows, Codex y validación. */

export const CODEX_VIEW = {
  es: {
    eyebrow: 'Lenguaje compartido',
    lede: 'La taxonomía para convertir observaciones visuales en evidencia consistente.',
  },
  en: {
    eyebrow: 'Shared language',
    lede: 'The taxonomy that turns visual observations into consistent evidence.',
  },
}

export const WORKBENCH = {
  es: {
    seek: 'Posición del video',
    back5: '5 frames atrás',
    prevFrame: 'Frame anterior',
    play: 'Reproducir',
    pause: 'Pausar',
    nextFrame: 'Frame siguiente',
    forward5: '5 frames adelante',
    loop: 'Loop',
    zoomOut: 'Reducir zoom',
    zoomIn: 'Aumentar zoom',
    dragToMark: 'Arrastrá para marcar el artefacto',
    clearSelection: 'Borrar selección',
    tools: 'Herramientas',
    speed: 'Velocidad',
    markIn: 'Marcar entrada',
    markOut: 'Marcar salida',
    zoomLevel: 'Nivel de zoom',
    addIssueOn: 'Issue en',
    outputSwitch: 'Elegir output',
  },
  en: {
    seek: 'Video position',
    back5: 'Back 5 frames',
    prevFrame: 'Previous frame',
    play: 'Play',
    pause: 'Pause',
    nextFrame: 'Next frame',
    forward5: 'Forward 5 frames',
    loop: 'Loop',
    zoomOut: 'Zoom out',
    zoomIn: 'Zoom in',
    dragToMark: 'Drag to mark the artifact',
    clearSelection: 'Clear selection',
    tools: 'Tools',
    speed: 'Speed',
    markIn: 'Mark in',
    markOut: 'Mark out',
    zoomLevel: 'Zoom level',
    addIssueOn: 'Issue on',
    outputSwitch: 'Choose output',
  },
}

export const QUEUE = {
  es: {
    eyebrow: 'Mesa de evaluación',
    title: 'Workflows',
    lede: 'Tus asignaciones, el Codex y las herramientas de inspección en un mismo lugar.',
    pending: 'pendientes',
    emptyTitle: 'No tenés workflows asignados',
    emptyLede: 'Cuando el equipo asigne una práctica o evaluación va a aparecer acá.',
    inProgress: 'En progreso',
    delivered: 'Entregadas',
    emptySection: 'No hay tareas en esta sección.',
    sent: 'Enviada',
    draft: 'Borrador',
    fresh: 'Nueva',
  },
  en: {
    eyebrow: 'Evaluation desk',
    title: 'Workflows',
    lede: 'Your assignments, the Codex and the inspection tools in one place.',
    pending: 'pending',
    emptyTitle: 'No workflows assigned yet',
    emptyLede: 'When the team assigns a practice or evaluation it will show up here.',
    inProgress: 'In progress',
    delivered: 'Delivered',
    emptySection: 'No tasks in this section.',
    sent: 'Submitted',
    draft: 'Draft',
    fresh: 'New',
  },
}

export const CODEX_PANEL = {
  es: {
    search: 'Buscar tag o categoría',
    empty: 'Sin resultados.',
    definition: 'Definición',
    useWhen: 'Cuándo usarlo',
    doNotUseWhen: 'Cuándo no usarlo',
  },
  en: {
    search: 'Search tag or category',
    empty: 'No results.',
    definition: 'Definition',
    useWhen: 'Use when',
    doNotUseWhen: 'Do not use when',
  },
}

export const WORKSPACE = {
  es: {
    notFound: 'Tarea no encontrada',
    unavailable: 'Tarea no disponible',
    unavailableLede: 'Esta evaluación no está asignada a tu cuenta.',
    back: 'Volver',
    backToWorkflows: 'Workflows',
    sent: 'Enviada',
    saving: 'Guardando…',
    savedState: 'Guardada',
    draft: 'Borrador',
    prompt: 'Prompt',
    objective: 'Objetivo',
    noPrompt: 'Sin prompt',
    noObjective: 'Sin objetivo adicional',
    priority: 'Prioridad',
    generalCriteria: 'Criterio general',
    ledger: 'Registro de evidencia',
    issues: 'Issues',
    hideCodex: 'Ocultar Codex',
    openCodex: 'Abrir Codex',
    removeIssue: 'Eliminar issue',
    noIssues: 'Todavía no marcaste evidencia. Pausá el video y agregá un issue sobre el output correspondiente.',
    structuredResult: 'Resultado estructurado',
    taskNotes: 'Notas de tarea',
    exportPreview: 'Vista previa del export JSON',
    saveDraft: 'Guardar borrador',
    submit: 'Enviar evaluación',
    codex: 'Aurum Codex',
    closeCodex: 'Cerrar Codex',
  },
  en: {
    notFound: 'Task not found',
    unavailable: 'Task unavailable',
    unavailableLede: 'This evaluation is not assigned to your account.',
    back: 'Back',
    backToWorkflows: 'Workflows',
    sent: 'Submitted',
    saving: 'Saving…',
    savedState: 'Saved',
    draft: 'Draft',
    prompt: 'Prompt',
    objective: 'Objective',
    noPrompt: 'No prompt',
    noObjective: 'No additional objective',
    priority: 'Priority',
    generalCriteria: 'General criteria',
    ledger: 'Evidence ledger',
    issues: 'Issues',
    hideCodex: 'Hide Codex',
    openCodex: 'Open Codex',
    removeIssue: 'Remove issue',
    noIssues: 'No evidence flagged yet. Pause the video and add an issue on the matching output.',
    structuredResult: 'Structured result',
    taskNotes: 'Task notes',
    exportPreview: 'JSON export preview',
    saveDraft: 'Save draft',
    submit: 'Submit evaluation',
    codex: 'Aurum Codex',
    closeCodex: 'Close Codex',
  },
}

export const STAGE_UI = {
  es: {
    stage: 'Etapa',
    context: 'Contexto',
    inspection: 'Inspección',
    annotation: 'Anotación',
    decision: 'Decisión',
    review: 'Revisión',
    contextHint: 'Prompt, objetivo y prioridad de la tarea.',
    inspectionHint: 'Mirá el material completo antes de decidir.',
    annotationHint: 'Marcá la evidencia que sostiene tu decisión.',
    decisionHint: 'Completá el resultado estructurado.',
    reviewHint: 'Revisá el resumen y enviá.',
    optional: 'Opcional',
    pending: 'Pendiente',
    complete: 'Listo',
    progress: 'Progreso',
    prev: 'Anterior',
    next: 'Siguiente',
    goToPending: 'Ir a lo que falta',
    openCodex: 'Codex',
    summaryTitle: 'Resumen de la evaluación',
    submittedTitle: 'Evaluación enviada',
    submittedLede: 'Quedó registrada. Ya no se puede editar.',
    nextTask: 'Siguiente tarea',
    noNextTask: 'No te quedan evaluaciones pendientes.',
    backToQueue: 'Volver a la cola',
    jsonToggle: 'Ver JSON del export',
  },
  en: {
    stage: 'Stage',
    context: 'Context',
    inspection: 'Inspection',
    annotation: 'Annotation',
    decision: 'Decision',
    review: 'Review',
    contextHint: 'Prompt, objective and priority of the task.',
    inspectionHint: 'Watch the full material before deciding.',
    annotationHint: 'Flag the evidence backing your decision.',
    decisionHint: 'Complete the structured result.',
    reviewHint: 'Check the summary and submit.',
    optional: 'Optional',
    pending: 'Pending',
    complete: 'Done',
    progress: 'Progress',
    prev: 'Previous',
    next: 'Next',
    goToPending: 'Go to what is missing',
    openCodex: 'Codex',
    summaryTitle: 'Evaluation summary',
    submittedTitle: 'Evaluation submitted',
    submittedLede: 'It is on record and can no longer be edited.',
    nextTask: 'Next task',
    noNextTask: 'You have no pending evaluations left.',
    backToQueue: 'Back to the queue',
    jsonToggle: 'View export JSON',
  },
}

export const SUMMARY_LABELS = {
  es: {
    verdict: 'Veredicto',
    preferred: 'Output preferido',
    ranking: 'Ranking',
    primaryReason: 'Razón principal',
    justification: 'Justificación observable',
    averageScore: 'Puntaje promedio',
    recommendation: 'Recomendación',
    eventCount: 'Eventos anotados',
    summary: 'Síntesis',
    adherence: 'Adherencia al prompt',
    transitionCount: 'Transiciones revisadas',
    transitionFailures: 'Transiciones con falla',
    decision: 'Decisión',
    offset: 'Desfase medido',
    evidence: 'Evidencia',
    severity: 'Severidad',
    expected: 'Esperado',
    observed: 'Observado',
    level: 'Nivel de riesgo',
    category: 'Categoría',
    policyRef: 'Referencia de política',
    scenario: 'Escenario',
    failureMode: 'Modo de falla',
    reproducibility: 'Reproducibilidad',
    issueCount: 'Issues registrados',
    criticalIssues: 'Issues altos o críticos',
    notes: 'Notas',
  },
  en: {
    verdict: 'Verdict',
    preferred: 'Preferred output',
    ranking: 'Ranking',
    primaryReason: 'Primary reason',
    justification: 'Observable justification',
    averageScore: 'Average score',
    recommendation: 'Recommendation',
    eventCount: 'Annotated events',
    summary: 'Synthesis',
    adherence: 'Prompt adherence',
    transitionCount: 'Transitions reviewed',
    transitionFailures: 'Failing transitions',
    decision: 'Decision',
    offset: 'Measured offset',
    evidence: 'Evidence',
    severity: 'Severity',
    expected: 'Expected',
    observed: 'Observed',
    level: 'Risk level',
    category: 'Category',
    policyRef: 'Policy reference',
    scenario: 'Scenario',
    failureMode: 'Failure mode',
    reproducibility: 'Reproducibility',
    issueCount: 'Logged issues',
    criticalIssues: 'High or critical issues',
    notes: 'Notes',
  },
}

export const WORKFLOW_UI = {
  es: {
    queueTitle: 'Workflows',
    queueLede: 'Tareas asignadas para evaluar.',
    pending: 'Pendientes',
    submitted: 'Enviadas',
    emptyQueue: 'No tenés tareas asignadas todavía.',
    back: 'Volver',
    saving: 'Guardando…',
    saved: 'Guardado',
    submit: 'Enviar evaluación',
    submitted_: 'Evaluación enviada',
    readOnly: 'Evaluación enviada — no editable.',
    addIssue: 'Agregar issue',
    issues: 'Issues',
    noIssues: 'Sin issues marcados todavía.',
    notes: 'Notas internas',
    notesHint: 'No viajan al export.',
    prompt: 'Prompt',
    clientObjective: 'Objetivo del cliente',
    evaluationPriority: 'Prioridad de evaluación',
    codex: 'Aurum Codex',
    codexSearch: 'Buscar tag, categoría…',
    codexEmpty: 'Sin resultados.',
    definition: 'Definición',
    useWhen: 'Cuándo usarlo',
    doNotUseWhen: 'Cuándo no usarlo',
    unanswered: 'sin responder',
    export: 'Export — señal lista para entrenamiento',
    viewJson: 'Ver JSON completo',
    hideJson: 'Ocultar JSON',
    copyJson: 'Copiar JSON',
    copied: 'Copiado',
  },
  en: {
    queueTitle: 'Workflows',
    queueLede: 'Tasks assigned for evaluation.',
    pending: 'Pending',
    submitted: 'Submitted',
    emptyQueue: 'No tasks assigned yet.',
    back: 'Back',
    saving: 'Saving…',
    saved: 'Saved',
    submit: 'Submit evaluation',
    submitted_: 'Evaluation submitted',
    readOnly: 'Evaluation submitted — read only.',
    addIssue: 'Add issue',
    issues: 'Issues',
    noIssues: 'No issues flagged yet.',
    notes: 'Internal notes',
    notesHint: 'They never reach the export.',
    prompt: 'Prompt',
    clientObjective: 'Client objective',
    evaluationPriority: 'Evaluation priority',
    codex: 'Aurum Codex',
    codexSearch: 'Search tag, category…',
    codexEmpty: 'No results.',
    definition: 'Definition',
    useWhen: 'Use when',
    doNotUseWhen: 'Do not use when',
    unanswered: 'unanswered',
    export: 'Export — training-ready signal',
    viewJson: 'View full JSON',
    hideJson: 'Hide JSON',
    copyJson: 'Copy JSON',
    copied: 'Copied',
  },
}

export const ISSUE_DIALOG = {
  es: {
    eyebrow: 'Captura de evidencia',
    title: 'Issue',
    close: 'Cerrar',
    start: 'Inicio',
    end: 'Fin',
    frame: 'Frame',
    severity: 'Severidad',
    confidence: 'Confianza',
    affectedArea: 'Área afectada',
    areaPlaceholder: 'Mano derecha, fondo, reflejo…',
    evidence: 'Justificación observable',
    evidencePlaceholder: 'Qué ocurre, dónde ocurre y por qué constituye un error.',
    spatial: 'Selección espacial',
    noCapture: 'El video no permitió capturar este frame. El issue temporal se puede guardar sin bbox.',
    cancel: 'Cancelar',
    confirm: 'Agregar issue',
    unanswered: 'sin responder',
  },
  en: {
    eyebrow: 'Evidence capture',
    title: 'Issue',
    close: 'Close',
    start: 'Start',
    end: 'End',
    frame: 'Frame',
    severity: 'Severity',
    confidence: 'Confidence',
    affectedArea: 'Affected area',
    areaPlaceholder: 'Right hand, background, reflection…',
    evidence: 'Observable justification',
    evidencePlaceholder: 'What happens, where it happens and why it is an error.',
    spatial: 'Spatial selection',
    noCapture: 'This frame could not be captured. The temporal issue can still be saved without a bbox.',
    cancel: 'Cancel',
    confirm: 'Add issue',
    unanswered: 'unanswered',
  },
}

export const WORKFLOW_FORM = {
  es: {
    select: 'Seleccionar…',
    preferredOutput: 'Output preferido',
    tie: 'Empate',
    neither: 'Ninguno sirve',
    ranking: 'Ranking de outputs',
    rankingHint: 'Tocá los outputs del mejor al peor. El primero queda como preferido.',
    clearRanking: 'Reiniciar ranking',
    primaryReason: 'Razón principal',
    justification: 'Justificación observable',
    justificationPlaceholder: 'Nombrá el criterio decisivo y la evidencia concreta.',
    qcVerdict: 'Veredicto QC',
    recommendation: 'Recomendación',
    temporalEvents: 'Eventos temporales',
    event: 'Evento',
    subject: 'Sujeto',
    action: 'Acción',
    object: 'Objeto',
    start: 'Inicio',
    end: 'Fin',
    summary: 'Resumen',
    second: 'segundo',
    evidence: 'Evidencia',
    transitions: 'Transiciones',
    transition: 'Transición',
    styleVerdict: 'Veredicto de estilo',
    decision: 'Decisión',
    offsetMs: 'Offset (ms)',
    offsetPlaceholder: 'sin medir',
    markerSec: 'Marcador (s)',
    markerPlaceholder: 'sin marcar',
    expected: 'Comportamiento esperado',
    observed: 'Comportamiento observado',
    severity: 'Severidad',
    riskCategory: 'Categoría de riesgo',
    level: 'Nivel',
    policyRef: 'Referencia de política',
    scenario: 'Escenario',
    attackVector: 'Vector de ataque',
    failureMode: 'Modo de falla',
    reproducibility: 'Reproducibilidad',
    unanswered: 'sin responder',
    remove: 'Quitar',
  },
  en: {
    select: 'Select…',
    preferredOutput: 'Preferred output',
    tie: 'Tie',
    neither: 'Neither works',
    ranking: 'Output ranking',
    rankingHint: 'Tap the outputs from best to worst. The first one becomes the preferred output.',
    clearRanking: 'Reset ranking',
    primaryReason: 'Primary reason',
    justification: 'Observable justification',
    justificationPlaceholder: 'Name the deciding criterion and the concrete evidence.',
    qcVerdict: 'QC verdict',
    recommendation: 'Recommendation',
    temporalEvents: 'Temporal events',
    event: 'Event',
    subject: 'Subject',
    action: 'Action',
    object: 'Object',
    start: 'Start',
    end: 'End',
    summary: 'Summary',
    second: 'second',
    evidence: 'Evidence',
    transitions: 'Transitions',
    transition: 'Transition',
    styleVerdict: 'Style verdict',
    decision: 'Decision',
    offsetMs: 'Offset (ms)',
    offsetPlaceholder: 'not measured',
    markerSec: 'Marker (s)',
    markerPlaceholder: 'not marked',
    expected: 'Expected behaviour',
    observed: 'Observed behaviour',
    severity: 'Severity',
    riskCategory: 'Risk category',
    level: 'Level',
    policyRef: 'Policy reference',
    scenario: 'Scenario',
    attackVector: 'Attack vector',
    failureMode: 'Failure mode',
    reproducibility: 'Reproducibility',
    unanswered: 'unanswered',
    remove: 'Remove',
  },
}

/** Etiquetas de los valores enumerados que se ven en los selects. */
export const ENUM_LABELS = {
  es: {
    low: 'Baja',
    medium: 'Media',
    high: 'Alta',
    critical: 'Crítica',
    pass: 'Correcto',
    marginal: 'Marginal',
    fail: 'No pasa',
    minor: 'Menor',
    major: 'Grave',
    blocking: 'Bloqueante',
    na: 'N/C',
    on_brand: 'Fiel a la marca',
    mostly_aligned: 'Mayormente alineado',
    partially_aligned: 'Parcialmente alineado',
    off_brand: 'Fuera de marca',
    reject: 'Rechazar',
    acceptable: 'Aceptable',
    useful_negative: 'Negativo útil',
    plausible: 'Plausible',
    minor_issue: 'Problema menor',
    major_issue: 'Problema grave',
    impossible: 'Imposible',
    safe: 'Seguro',
    safe_with_notes: 'Seguro con observaciones',
    needs_policy_review: 'Requiere revisión de política',
    escalate: 'Escalar',
    block: 'Bloquear — no usar',
    fulfilled: 'Cumplido',
    partial: 'Parcial',
    missing: 'Ausente',
    wrong: 'Incorrecto',
    once: 'Una vez',
    consistency_attack: 'Ataque de consistencia',
    identity_forgery: 'Falsificación de identidad',
    semantic_mismatch: 'Desajuste semántico',
    style_bypass: 'Elusión de estilo',
    prompt_injection: 'Inyección de prompt',
    other: 'Otro',
    identity_not_preserved: 'Identidad no preservada',
    temporal_incoherence: 'Incoherencia temporal',
    anatomy_failure: 'Falla anatómica',
    physics_failure: 'Falla física',
    hallucinated_element: 'Elemento alucinado',
    safety_policy_breach: 'Violación de política de safety',
  },
  en: {
    low: 'Low',
    medium: 'Medium',
    high: 'High',
    critical: 'Critical',
    pass: 'Pass',
    marginal: 'Marginal',
    fail: 'Fail',
    minor: 'Minor',
    major: 'Major',
    blocking: 'Blocking',
    na: 'N/A',
    on_brand: 'On brand',
    mostly_aligned: 'Mostly aligned',
    partially_aligned: 'Partially aligned',
    off_brand: 'Off brand',
    reject: 'Reject',
    acceptable: 'Acceptable',
    useful_negative: 'Useful negative',
    plausible: 'Plausible',
    minor_issue: 'Minor issue',
    major_issue: 'Major issue',
    impossible: 'Impossible',
    safe: 'Safe',
    safe_with_notes: 'Safe with notes',
    needs_policy_review: 'Needs policy review',
    escalate: 'Escalate',
    block: 'Block — do not use',
    fulfilled: 'Fulfilled',
    partial: 'Partial',
    missing: 'Missing',
    wrong: 'Wrong',
    once: 'Once',
    consistency_attack: 'Consistency attack',
    identity_forgery: 'Identity forgery',
    semantic_mismatch: 'Semantic mismatch',
    style_bypass: 'Style bypass',
    prompt_injection: 'Prompt injection',
    other: 'Other',
    identity_not_preserved: 'Identity not preserved',
    temporal_incoherence: 'Temporal incoherence',
    anatomy_failure: 'Anatomy failure',
    physics_failure: 'Physics failure',
    hallucinated_element: 'Hallucinated element',
    safety_policy_breach: 'Safety policy breach',
  },
}

/**
 * Mensajes de validación. `validateEvaluation` devuelve códigos (no texto) para
 * que el mismo resultado se pueda mostrar en cualquier idioma y testear sin
 * depender de la traducción.
 */
export const VALIDATION = {
  es: {
    verdict_required: 'Elegí un veredicto.',
    ranking_required: 'Ordená todos los outputs, sin repetir posiciones.',
    primary_reason_required: 'Indicá la razón principal.',
    justification_required: 'Escribí la justificación observable.',
    scores_required: 'Puntuá todas las dimensiones. El 0 vale, pero hay que elegirlo.',
    events_required: 'Agregá al menos un evento temporal.',
    event_detail_required: 'Cada evento necesita sujeto o acción para ser interpretable.',
    items_required: 'Evaluá al menos un elemento del prompt.',
    item_status_required: 'Marcá el estado de cada elemento del prompt.',
    transitions_required: 'Evaluá al menos una transición.',
    transition_status_required: 'Marcá el estado de cada transición.',
    decision_required: 'Completá la decisión final.',
    offset_required: 'Indicá el offset medido en milisegundos.',
    severity_required: 'Elegí la severidad.',
    expected_observed_required: 'Describí qué se esperaba y qué se observó.',
    level_required: 'Elegí el nivel de riesgo.',
    scenario_required: 'Completá escenario y modo de falla.',
    reproducibility_required: 'Indicá la reproducibilidad.',
  },
  en: {
    verdict_required: 'Choose a verdict.',
    ranking_required: 'Rank every output, with no repeated positions.',
    primary_reason_required: 'State the primary reason.',
    justification_required: 'Write the observable justification.',
    scores_required: 'Score every dimension. 0 is valid, but you have to choose it.',
    events_required: 'Add at least one temporal event.',
    event_detail_required: 'Every event needs a subject or an action to be readable.',
    items_required: 'Evaluate at least one prompt element.',
    item_status_required: 'Set the status of every prompt element.',
    transitions_required: 'Evaluate at least one transition.',
    transition_status_required: 'Set the status of every transition.',
    decision_required: 'Complete the final decision.',
    offset_required: 'Enter the measured offset in milliseconds.',
    severity_required: 'Choose the severity.',
    expected_observed_required: 'Describe what was expected and what was observed.',
    level_required: 'Choose the risk level.',
    scenario_required: 'Complete scenario and failure mode.',
    reproducibility_required: 'State the reproducibility.',
  },
}

/**
 * Taglines de los diez workflows. Los títulos quedan como están: son nombres
 * técnicos del producto y no se traducen.
 */
export const WORKFLOW_TAGLINES = {
  es: {
    preference_evaluation: 'Compará outputs y defendé una preferencia.',
    single_video_qc: 'Decidí si un video sirve y documentá sus fallas.',
    event_temporal_annotation: 'Describí qué ocurre y en qué momento.',
    prompt_adherence: 'Medí cuánto cumple el video la instrucción.',
    continuity_coherence: 'Evaluá si los planos sostienen una escena.',
    style_consistency: 'Revisá lenguaje visual, marca y cinematografía.',
    audio_visual_sync: 'Medí la alineación entre imagen y sonido.',
    physics_behavior: 'Detectá interacciones físicamente imposibles.',
    safety_compliance: 'Auditá riesgo, política y aptitud de publicación.',
    adversarial_red_team: 'Provocá y documentá fallas reproducibles.',
  },
  en: {
    preference_evaluation: 'Compare outputs and defend a preference.',
    single_video_qc: 'Decide whether a video works and document its failures.',
    event_temporal_annotation: 'Describe what happens and when.',
    prompt_adherence: 'Measure how far the video meets the instruction.',
    continuity_coherence: 'Judge whether the shots hold one scene together.',
    style_consistency: 'Review visual language, brand and cinematography.',
    audio_visual_sync: 'Measure the alignment between image and sound.',
    physics_behavior: 'Spot physically impossible interactions.',
    safety_compliance: 'Audit risk, policy and readiness to publish.',
    adversarial_red_team: 'Provoke and document reproducible failures.',
  },
}

/**
 * Razones principales del workflow de preferencia.
 *
 * La clave es el valor que se guarda en la evaluación (español, canónico), así
 * traducir la interfaz no invalida las evaluaciones ya enviadas. Si falta una
 * traducción se muestra la clave tal cual.
 */
export const DEFAULT_REASON_LABELS = {
  es: {
    'Mayor consistencia temporal': 'Mayor consistencia temporal',
    'Mejor adherencia al prompt': 'Mejor adherencia al prompt',
    'Movimiento más plausible': 'Movimiento más plausible',
    'Mayor calidad cinematográfica': 'Mayor calidad cinematográfica',
    'Más listo para producción': 'Más listo para producción',
  },
  en: {
    'Mayor consistencia temporal': 'Stronger temporal consistency',
    'Mejor adherencia al prompt': 'Better prompt adherence',
    'Movimiento más plausible': 'More plausible motion',
    'Mayor calidad cinematográfica': 'Higher cinematic quality',
    'Más listo para producción': 'Closer to production ready',
  },
}

/**
 * Texto del Codex por tag. Las etiquetas y categorías son vocabulario técnico
 * compartido y no se traducen; sí se traduce lo que el evaluador tiene que
 * entender para decidir.
 */
export const CODEX_TEXT = {
  es: {
    'temporal-flicker': ['El brillo o la textura parpadean entre frames.', 'Usalo cuando el cambio no pertenece a una fuente de luz de la escena.', 'No usar para luces diegéticas que titilan.'],
    'morphing-artifact': ['Un objeto se derrite, fusiona o transforma de forma no física.', 'Usalo cuando la geometría cambia sin una causa narrativa.', 'No usar si el prompt pidió la transformación.'],
    'compression-artifact': ['Bloques o degradación causada por compresión.', 'Usalo cuando hay macroblocking localizado y visible.', 'No usar para grano estilístico.'],
    'identity-drift': ['La identidad de una persona cambia durante el plano.', 'Usalo cuando los rasgos dejan de pertenecer al mismo sujeto.', 'No usar para un corte intencional a otra persona.'],
    'object-permanence-failure': ['Un objeto aparece, desaparece o se teletransporta.', 'Usalo cuando no existe corte ni oclusión que lo explique.', 'No usar si el objeto salió naturalmente de cuadro.'],
    'background-inconsistency': ['El fondo cambia independientemente de la cámara.', 'Usalo para texturas o elementos que mutan sin causa.', 'No usar para elementos animados de la escena.'],
    'melted-hands': ['Los dedos se fusionan o pierden estructura anatómica.', 'Usalo cuando la mano es suficientemente visible.', 'No usar si la mano está demasiado lejos u ocluida.'],
    'face-deformation': ['Los rasgos faciales están deformados o desalineados.', 'Usalo cuando la deformación es clara y no estilística.', 'No usar para estilos cartoon o efectos pedidos.'],
    'text-generation-failure': ['El texto visible es ilegible o contiene caracteres sin sentido.', 'Usalo cuando el texto debería poder leerse.', 'No usar para texto deliberadamente desenfocado.'],
    'depth-inconsistency': ['Los elementos rompen el orden esperado de profundidad.', 'Usalo cuando foreground y background se cruzan de forma imposible.', 'No usar para perspectiva estilizada intencional.'],
    'floating-objects': ['Un objeto parece flotar sin apoyo.', 'Usalo cuando debería existir contacto con una superficie.', 'No usar si el prompt establece levitación.'],
    'framing-jump': ['La composición salta dentro de un plano continuo.', 'Usalo para cambios bruscos sin corte.', 'No usar cuando hay un corte explícito.'],
    'hand-object-failure': ['Una mano atraviesa o sostiene mal un objeto.', 'Usalo cuando el contacto es físicamente imposible.', 'No usar si la oclusión vuelve ambiguo el contacto.'],
    'gravity-violation': ['Un objeto ignora la gravedad esperada.', 'Usalo cuando flota o cae en dirección imposible.', 'No usar en escenas con gravedad alterada.'],
    'lighting-inconsistency': ['La dirección o intensidad de luz contradice la escena.', 'Usalo cuando no hay una fuente que explique el cambio.', 'No usar si una fuente visible lo justifica.'],
    'shadow-direction-mismatch': ['La sombra contradice la fuente principal.', 'Usalo cuando dirección y fuente son incompatibles.', 'No usar si hay varias fuentes plausibles.'],
    'color-banding': ['Se ven escalones en un gradiente que debería ser suave.', 'Usalo cuando las bandas son visibles a tamaño normal.', 'No usar para estética pixelada intencional.'],
    'sub-frame-jitter': ['Un objeto vibra uno o dos píxeles sin causa.', 'Usalo para micro-movimiento temporal no motivado.', 'No usar cuando existe vibración real en escena.'],
    'prompt-omission': ['Falta un elemento requerido por el prompt.', 'Usalo cuando el requisito es explícito.', 'No usar para elementos opcionales o ambiguos.'],
    'action-mismatch': ['La acción no coincide con la solicitada.', 'Usalo cuando el sujeto ejecuta otra acción.', 'No usar para variaciones menores de ejecución.'],
  },
  en: {
    'temporal-flicker': ['Brightness or texture flickers between frames.', 'Use it when the change does not belong to a light source in the scene.', 'Do not use it for diegetic lights that flicker.'],
    'morphing-artifact': ['An object melts, fuses or transforms in a non-physical way.', 'Use it when geometry changes without a narrative cause.', 'Do not use it if the prompt asked for the transformation.'],
    'compression-artifact': ['Blocking or degradation caused by compression.', 'Use it when macroblocking is localized and visible.', 'Do not use it for stylistic grain.'],
    'identity-drift': ['A person’s identity changes during the shot.', 'Use it when the features stop belonging to the same subject.', 'Do not use it for an intentional cut to another person.'],
    'object-permanence-failure': ['An object appears, disappears or teleports.', 'Use it when no cut or occlusion explains it.', 'Do not use it if the object naturally left the frame.'],
    'background-inconsistency': ['The background changes independently of the camera.', 'Use it for textures or elements that mutate without cause.', 'Do not use it for animated scene elements.'],
    'melted-hands': ['Fingers fuse or lose anatomical structure.', 'Use it when the hand is visible enough.', 'Do not use it if the hand is too far or occluded.'],
    'face-deformation': ['Facial features are deformed or misaligned.', 'Use it when the deformation is clear and not stylistic.', 'Do not use it for cartoon styles or requested effects.'],
    'text-generation-failure': ['Visible text is illegible or contains nonsense characters.', 'Use it when the text should be readable.', 'Do not use it for deliberately defocused text.'],
    'depth-inconsistency': ['Elements break the expected depth order.', 'Use it when foreground and background cross impossibly.', 'Do not use it for intentional stylized perspective.'],
    'floating-objects': ['An object appears to float without support.', 'Use it when contact with a surface should exist.', 'Do not use it if the prompt establishes levitation.'],
    'framing-jump': ['Composition jumps within a continuous shot.', 'Use it for abrupt changes without a cut.', 'Do not use it when there is an explicit cut.'],
    'hand-object-failure': ['A hand passes through or badly holds an object.', 'Use it when the contact is physically impossible.', 'Do not use it if occlusion makes the contact ambiguous.'],
    'gravity-violation': ['An object ignores expected gravity.', 'Use it when it floats or falls in an impossible direction.', 'Do not use it in scenes with altered gravity.'],
    'lighting-inconsistency': ['Light direction or intensity contradicts the scene.', 'Use it when no source explains the change.', 'Do not use it if a visible source justifies it.'],
    'shadow-direction-mismatch': ['The shadow contradicts the main source.', 'Use it when direction and source are incompatible.', 'Do not use it if several sources are plausible.'],
    'color-banding': ['Steps appear in a gradient that should be smooth.', 'Use it when the bands are visible at normal size.', 'Do not use it for intentional pixel aesthetics.'],
    'sub-frame-jitter': ['An object vibrates one or two pixels without cause.', 'Use it for unmotivated temporal micro-movement.', 'Do not use it when real vibration exists in the scene.'],
    'prompt-omission': ['An element required by the prompt is missing.', 'Use it when the requirement is explicit.', 'Do not use it for optional or ambiguous elements.'],
    'action-mismatch': ['The action does not match the requested one.', 'Use it when the subject performs another action.', 'Do not use it for minor execution variations.'],
  },
}
